affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: simcax/dotime
  tag: 0.0.63
imagePullSecrets: []
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
    nginx.org/proxy-connect-timeout: 30s
    nginx.org/proxy-read-timeout: 20s
  enabled: true
  hosts:
  - host: dev.dotime.me
    paths:
    - backend:
        serviceName: dotime-me
        servicePort: 80
      path: /
  tls:
  - hosts:
    - dev.dotime.me
    secretName: dev-dotime-tls
minAvailable: 1
nameOverride: ''
nameSpace: dotime-me-dev
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 2
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []
volumeMounts:
- mountPath: /root/.postgresql
  name: cockroachdb-ssl-cert-volume
  readOnly: true
volumes:
- name: cockroachdb-ssl-cert-volume
  secretName: cockroach-ssl-cert
