# This is a basic workflow to help you get started with Actions

name: Testing HELM Charts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - name: Lint the HELM Chart
        run: |
          helm version
          helm lint dotime-me --values dotime-me/values-dev.yaml
      - name: Install DaTree HELM Plugin
        run: |
          helm plugin install https://github.com/datreeio/helm-datree
          helm datree test --ignore-missing-schemas dotime-me -- --values dotime-me/values-dev.yaml