# This is a basic workflow to help you get started with Actions

name: Testing HELM Charts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - name: Test helm is here
        run: |
          helm version
